#!/usr/bin/env bash

set -Eeuo pipefail


USAGE="usage: set-wakeup"

usage() {
    echo "${USAGE}"
}

help() {
cat <<help

DESCRIPTION

    Script that enables wakeup if the computer is plugged into power and connected to external monitors (i.e.: docked) and disables wakeup if either of those things isn't true.

    Intended to run as a root user cron.

USAGE

    ${USAGE}

OPTIONS

    -h, --help          display this message
help
}


while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      help
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done

# FIXME: why does this only seem to work when --verbose is used?
if check-monitors -e && check-power -s ac; then
    enable-wakeup --verbose
else
    disable-wakeup --verbose
fi

