#!/usr/bin/env bash

set -Eeuo pipefail

source "${BASH_LIB}/args/check.sh"
source "${BASH_LIB}/utils/sys.sh"


OS="$(sys::os_type)"
MGR="${OS}-pkgmgr"

if ! check::installed "${MGR}"; then
    ulogger error "no known package manager for os=${OS} (pkgmgr=${MGR})"
    exit 1
fi

"${MGR}" "$@"

