#!/bin/bash

set -euo pipefail

source "utils.sh"


<< comment
This script has a few outstanding TODOs:

  * just getting it to generally work: it seems to work on the first run of some
    new method (first ./load-secrets, then sh load-secrets), but then stop actually
    putting the env vars into the environment
  * there's a more performant way to do query fields across the same secret, 
    but it's --challenging-- a nightmare to express in bash; try to figure this
    out (probably means moving to another language, then calling from bash to 
    load the env vars) 
  * adding proper logging
  * adding a cronjob to call this regularly

comment


function help() {
cat << EOF

Description

    This script loads secrets, as specified in the file set in \$SECRET_FILE_SRC, into the 
    environment. If \$SECRET_FILE_SRC is unset, the default "\$HOME/.config/secrets" will be
    used. If the relevant file does not exist, this script will exit w/ a 0 return code.

    Secrets in the relevant source file should be of the following form:

        NAME_OF_ENV_VAR_TO_LOAD,1password-secret-id,1password-secret-field

    In the above example, the value of "1password-secret-field" queried from the 
    secret w/ ID = "1password-secret-id" will be loaded into an env var w/ 
    name = "NAME_OF_ENV_VAR_TO_LOAD".

    This script makes use of an md5 checksum to determine if action needs to be taken: if the
    checksum of \$SECRET_FILE_SRC is unchanged (stored at \$SRC_FILE_CHECKSUM), the script will 
    exit w/ a 0 return code. If \$SRC_FILE_CHECKSUM doesn't exist, the script will behave as it
    would have had the checksum failed. By default, the checksum file will live in the same
    directory as the source file and is named ".\$(basename \$SRC_FILE).md5".

Usage

    load-env [-h|--help] [-d|--dry-run] [-s|--source path/to/secrets] [-c|--checksum path/to/chekcsum] 

Options

    -h, --help
        Show this help message and exit.

    -d, --dry-run
        Logs state changes to stdout but makes no changes to env.

    -s, --source
        Allows caller to directly specify the secrets source file.

    -c, --checksum
        Allows caller to directly specify the secrets checksum file.

Note: This script assumes the following:

  * The 1password CLI executable, op, is installed and in the caller's path
  * API access has been granted in the relevant 1password organization
  * The relevant organization has already been authenticated

EOF
}


DRY_RUN=false
FORCE=false
SRC_FILE="${SECRET_FILE_SRC:-${HOME}/.config/secrets}" 
SRC_FILE_CHECKSUM="$(dirname ${SRC_FILE})/.$(basename ${SRC_FILE}).md5" 

add_secret_to_env() {
    id="${1}"
    env_name="${2}"
    field_name="${3}"

    value="$(op item get ${id} --fields ${field_name})"

    if [[ -z "${value}" ]]; then
        echo "Unable to retrieve value for ${id}.${field_name}"
        exit 1
    fi

    if [[ "$DRY_RUN" = "true" ]]; then
        echo "export \"${env_name}=${value}\""
    else
        export TEST="test"
        export ${env_name}="${value}"
    fi
}

while [[ $# -gt 0 ]]; do
    case $1 in
        -d|--dry-run)
            DRY_RUN=true
            shift
            ;;
        -s|--source)
            SRC_FILE="${2}"
            SRC_FILE_CHECKSUM="$(dirname ${SRC_FILE})/.$(basename ${SRC_FILE}).md5" 
            shift
            shift
            ;;
        -c|--checksum)
            SRC_FILE_CHECKSUM="${2}"
            shift
            shift
            ;;
        -f|--force)
            FORCE=true
            shift
            ;;
        -h|--help)
            shift 
            exit 0
            ;;
        *|-*|--*)
            help
            exit 1
            ;;
    esac
done
 
## main

if [[ $# > 0 ]]; then
    help
    exit 0
fi

[[ "${FORCE}" = "true" ]] && rm -f ${SRC_FILE_CHECKSUM}
[[ -f ${SRC_FILE} ]] || exit 0
[[ "$(md5_checksum ${SRC_FILE_CHECKSUM})" -eq 0 ]] && exit 0

[[ "${DRY_RUN}" = "true" ]] || rm -f ${SRC_FILE_CHECKSUM}

while IFS="," read -r ID ENV_NAME FIELD_NAME
do
    add_secret_to_env "${ID}" "${ENV_NAME}" "${FIELD_NAME}"
done < ${SRC_FILE}

[[ "${DRY_RUN}" = "true" ]] || md5 $SRC_FILE > ${SRC_FILE_CHECKSUM}

