#!/bin/bash

set -euo pipefail


function help() {
<<help
    A script that's intended to make file tree navigation a little easier.
help
}


FILE_TYPE=""
FIND_PATH=()
CMD=""
TYPE_MODIFIER=""
MAX_DEPTH=2

while [[ $# -gt 0 ]]; do
    case $1 in
     -c|--command)
      CMD="${2}"
      shift
      shift
      ;;
     -f|--file)
      TYPE_MODIFIER="-type f"
      shift
      ;;
     -d|--dir)
      TYPE_MODIFIER="-type d"
      shift
      ;;
     -m|--maxdepth)
      MAX_DEPTH="${2}"
      shift
      shift
      ;;
     -h|--help)
      help
      exit 0
      ;;
     -*|--*)
      help
      exit 1
      ;;
     *)
      FIND_PATH+=("${1}")
      shift
      ;;
  esac
done

if [[ ${#FIND_PATH[@]} -eq 0 ]]; then
    FIND_PATH+=("$(pwd)")
fi

FOUND_PATH=$(find ${FIND_PATH} -maxdepth ${MAX_DEPTH} ${TYPE_MODIFIER} -not -path "*/\.git*" | fzf)

if [[ -z "${FOUND_PATH}" ]]; then
    exit 0
fi

if [[ -z "${CMD}" && -d "${FOUND_PATH}" ]]; then
    CMD="cd"
elif [[ -z "${CMD}" && -f "${FOUND_PATH}" ]]; then
    CMD="${EDITOR}"
fi

if [[ -n "${CMD}" ]]; then
    "${CMD}" "${FOUND_PATH}"
fi

