#!/usr/bin/env bash

set -Eeuo pipefail


USAGE="tq path [selector] [-s]"

usage() {
    echo "${USAGE}"
}

help() {
cat <<help
DESCRIPTION

    A small script that attempts to do for toml what jq does for json, or yq for yaml.

    Note: one small behavioral different b/w tq and jq/yq is that "null" values manifest as the empty string ("").

    Impl note: this script is a simple wrapper arounda toml -> json converter that calls jq.

USAGE

    ${USAGE}

POSITIONAL ARGUMENTS

    path            a path to a toml file
    selector        optional; a jq style selector
    *               all additional arguments can be considered as being passed directly to jq

OPTIONS

    -s, --suppress      optional; if provided, errors will be ignored: script output will be empty, rc=0
    -h, --help          optional; display this message
help
}


TOML_PATH=""
SELECTOR="."
ARGS=()
SUPPRESS=""

while [[ $# -gt 0 ]]; do
  case $1 in
    -s|--suppress)
      SUPPRESS="true"
      shift
      ;;
    -h|--help)
      help
      exit 0
      ;;
    *)
      ARGS+=("${1}")
      shift
      ;;
  esac
done


function __handle_suppression() {
    [[ "${SUPPRESS}" == "true" ]] && exit 0
}

# validate dependencies

if ! which jq &> /dev/null; then
    __handle_suppression
    echo "[ERROR] jq is required for tq"
    exit 1
fi

if ! which rq &> /dev/null; then
    __handle_suppression
    echo "[ERROR] rq is required for tq"
    exit 1
fi

# process arguments

[[ ${#ARGS[@]} -ge 1 ]] && TOML_PATH="${ARGS[0]}"
[[ ${#ARGS[@]} -ge 2 ]] && SELECTOR="${ARGS[1]}"
ARGS=("${ARGS[@]:2}")

# validate arguments

if [[ ! -f "${TOML_PATH}" ]]; then
    __handle_suppression
    echo "[ERROR] path (${TOML_PATH:-?}) must refer to a valid file"
    exit 1
fi

# execute

OUT="$(cat "${TOML_PATH}" | rq -t | rq -J | jq "${SELECTOR}" ${ARGS[*]})"
[[ "${OUT}" != "null" ]] && echo "${OUT}" || echo ""

