#!/usr/bin/env bash

set -Eeuo pipefail

source "/etc/profile.d/shared_paths.sh"


USAGE="deploy package {package} [-s] [-t] [-r] [-u] [-d] [-v 0..5]"

usage() {
    echo "${USAGE}"
}

help() {
cat <<help
DESCRIPTION

    A thin wrapper around stow for installing/removing internal and manually installed packages.

USAGE

    ${USAGE}

POSITIONAL ARGUMENTS

    PACKAGE             >= 1 required, multi-valued; paths to file/dirs to deploy

OPTIONS

    -s, --source        optional, defaults to cwd; the dir from which to install
    -t, --target        optional, defaults to the value of LOCAL_BIN or stow's default, depending on the availability of path related env variables; the dir to which to install
    -u, --uninstall     optional; indicates that packages should be remove
    -r, --reinstall     optional; indicates that packages should be remove
    -d, --dry-run       optional; simulate changes based on provided args but make no file system changes
    -v, --verbose       optional, -v N, N=0..5, defaults to 0; logs progress/status msgs to stderr; higher N means more verbosity
    -h, --help          optional; display this message
help
}


PKGS=()
SRC=""
TGT=""
MODIFIER=""
DRY_RUN=""
VERBOSE=""

while [[ $# -gt 0 ]]; do
  case $1 in
    -s|--source)
      SRC="--dir=${2}"
      shift
      shift
      ;;
    -t|--target)
      TGT="${2}"
      shift
      shift
      ;;
    -u|--uninstall)
      MODIFIER="--delete"
      shift
      ;;
    -r|--reinstall)
      MODIFIER="--restow"
      shift
      ;;
    -d|--dry-run)
      DRY_RUN="--no"
      shift
      ;;
    -v*)
      VERBOSE="$1"
      shift
      ;;
    -h|--help)
      help
      exit 0
      ;;
    -*)
      usage
      exit 1
      ;;
    *)
      PKGS+=("${1}")
      shift
      ;;
  esac
done


if [[ -z "${TGT}" ]] && [[ -z "${LOCAL_BIN+x}" ]]; then
    echo "[WARN] -t|--target not provided and LOCAL_BIN not set; falling back to stow default"
elif [[ -z "${TGT}" ]]; then
    TGT="${LOCAL_BIN}"
fi

if [[ "${#PKGS[@]}" -lt 1 ]]; then
    echo "[ERROR] at least one package is required"
    exit 1
fi

sudo stow "${SRC}" --target="${TGT}" ${MODIFIER} $DRY_RUN $VERBOSE "${PKGS[@]}"

