#!/usr/bin/env bash

set -Eeuo pipefail


USAGE="log-write level msg {msg} [-p prefix] [-t type] [-s normal|notify|log|force] [-n] [-c path]"

usage() {
    echo "${USAGE}"
}

help() {
cat <<help
DESCRIPTION

    User logger (i.e.: ulogger) that logs messages to files and/or stdout based on logger configuration and provided arguments.

    The only arguments required to make a logger call are a log level, -l|--log-level, and a message to log. Log levels can be any of the following:

        * trace - the most verbose, fine grained logging; useful for debugging
        * debug - verbose, fine grained logging; useful for debugging
        * info - messages about normal system operations
        * warn - messages about abnormal, but not necessarily dangerous, system operations
        * error - messages about abnormal, potentially dangerous system operations that are be considered errors

    Optionally, messages can be logged w/ a prefix, -p|--prefix, (for grouping related log lines), a type, -t|--type, (determines the file to which messages are logged),
    and a strategy, -s|--strategy. Strategies determine whether messages are written to a file, to stdout, or both. The following are valid strategies:

        * normal - the default strategy; lines are written to relevant log files, but are only logged to stdout if the provided log level is >= the current log level
        * notify - lines are only written to stdout, regardless of log level
        * log - lines are only written to relevant log files
        * force - lines are written to log files and stdout, regardless of the provided/current log levels

USAGE

    ${USAGE}

POSITIONAL ARGUMENTS

    MSG                 components of the message to be logged
    LEVEL               the log level of the message; determines which messages get logged to stdout; see log/log-level

OPTIONS

    -p, --prefix        optional; can also be set via the ULOGGER_PREFIX env var; a label w/ which to prefix log messages for enhanced logging granularity
    -t, --type          optional, defaults to "default"; can also be set via the ULOGGER_TYPE env var; determines the log file to which logs are written; provided types
                        are used to construct paths of the following form: "\${LOG_ROOT}/\${TYPE}.log"; if that file doesn't exist, it will be created
    -s, --strategy      optional, defaults to "normal"; can also be set via the ULOGGER_STRATEGY or ULOGGER_VERBOSE env vars; the former sets the "force" strategy;
                        possible values are "normal", "notify", "log", and "force"; determines where/how logs are written
    -n, --no-fmt        optional; if present, the log line won't be formatted w/ log level, prefix, date, etc.
    -c, --config        optional; a path to a file from which to read user ulogger config
    -h, --help          optional; display this message
help
}


declare -A STRATEGIES=([NORMAL]=1 [NOTIFY]=1 [LOG]=1 [FORCE]=1)

MSGS=""
LOG_LINE=""
LOG_LEVEL=""
PREFIX=""
STRATEGY="NORMAL"
NO_FMT=""
CONFIG_PATH=""


__to_upper() {
    local str="${1}"
    echo "${str}" | tr '[:lower:]' '[:upper:]'
}

__process_positional() {
    if [[ -z "${LOG_LEVEL}" ]]; then
        LOG_LEVEL="$(__to_upper "${1}")"
        log-level "${LOG_LEVEL}" -v || exit 1
    else
      MSGS="$([[ -z "${MSGS}" ]] && echo "${1}" || echo "${MSGS} ${1}")"
      LOG_LINE="${MSGS}"
    fi
}

[[ -n "${ULOGGER_PREFIX+x}" ]] && PREFIX="$(__to_upper "${ULOGGER_PREFIX}")"
[[ -n "${ULOGGER_VERBOSE+x}" ]] && [[ "${ULOGGER_VERBOSE}" == "true" ]] && STRATEGY="FORCE"
[[ -n "${ULOGGER_STRATEGY+x}" ]] && STRATEGY="$(__to_upper "${ULOGGER_STRATEGY}")"

while [[ $# -gt 0 ]]; do
  case $1 in
    -p|--prefix)
      [[ -z "${PREFIX}" ]] && PREFIX="$(__to_upper "${2}")"
      shift
      shift
      ;;
    -t|--type)
      export ULOGGER_TYPE="${2}"
      shift
      shift
      ;;
    -s|--strategy)
      [[ -z "${STRATEGY}" ]] && STRATEGY="$(__to_upper "${2}")"
      shift
      shift
      ;;
    -n|--no-fmt)
      NO_FMT="true"
      shift
      ;;
    -c|--config)
      CONFIG_PATH="${2}"
      shift
      shift
      ;;
    -h|--help)
      help
      exit 0
      ;;
    *)
      __process_positional "${1}"
      shift
      ;;
  esac
done


# arg validation

if [[ -z "${LOG_LEVEL}" ]]; then
    echo "[ERROR] -l|--log-level is required"
    exit 1
fi

if [[ -z "${STRATEGIES[${STRATEGY}]+x}" ]]; then
    STRATEGIES_STR="$(echo "${!STRATEGIES[*]}" | tr ' ' '|')"
    echo "[ERROR] -s|--strategy must be one of '${STRATEGIES_STR}', not '${STRATEGY}'"
    exit 1
fi

LOG_ROOT="$(log-config -f root -c "${CONFIG_PATH}")"
LOG_DIR="$(log-config -f dir -c "${CONFIG_PATH}")"
LOG_PATH="$(log-config -f path -c "${CONFIG_PATH}")"

# create log dir if it doesn't exist
[[ ! -d "${LOG_ROOT}" ]] && mkdir -p "${LOG_ROOT}"
# create log file's parent dir, if it doesn't exist
[[ ! -d "${LOG_DIR}" ]] && mkdir -p "${LOG_DIR}"
# create log file if it doesn't exist
[[ ! -f "${LOG_PATH}" ]] && touch "${LOG_PATH}"

# format log line, if necessary
if [[ -z "${NO_FMT}" ]]; then
    PREFIX="$([[ -n "${PREFIX}" ]] && echo "[$(__to_upper "${PREFIX}")] " || echo "")"
    LOG_LINE="[${LOG_LEVEL}] ${PREFIX}${LOG_LINE} ($(date))"
fi

# write to log file, if necessary
if [[ "${STRATEGY}" != "NOTIFY" ]]; then
    echo "${LOG_LINE}" >> "${LOG_PATH}"
fi

{ log-level "${LOG_LEVEL}"; ERR="$?"; } || true

# propagate unexpected error
if [[ ${ERR} -eq 2 ]]; then
    exit 1
# write to stdout, if necessary
elif [[ "${STRATEGY}" == "NORMAL" ]] && [[ "${ERR}" -eq 0 ]]; then
    echo "[${LOG_LEVEL}] ${MSGS}"
elif [[ "${STRATEGY}" == "FORCE" ]] || [[ "${STRATEGY}" == "NOTIFY" ]]; then
    echo "[${LOG_LEVEL}] ${MSGS}"
fi

