#!/usr/bin/env bash

# note: must be run in root user login shell (i.e.: sudo -i)

set -Eeuo pipefail


# make systemd dir, if necessary
mkdir -p /usr/local/systemd/
# install runnable
cp ${TOOLS_ROOT}/system/systemd/mv-stg-backups/mv-stg-backups /usr/local/systemd/
# install systemd user units
install-units -d ${TOOLS_ROOT}/system/systemd/mv-stg-backups -o user -t path

