#!/usr/bin/env bash

set -Eeuo pipefail

source "${BASH_LIB}/args/check.sh"
source "${BASH_LIB}/utils/sys.sh"


OS="$(sys::os_type)"
CTL="${OS}-wifictl"

if ! check_installed "${CTL}"; then
    ulogger error "no known wifictl for os=${OS} (wifictl=${CTL})"
    exit 1
fi

"${CTL}" "$@"

