#!/usr/bin/env bash

set -Eeuo pipefail

source "${BASH_LIB}/api/tmux.sh"
source "${BASH_LIB}/args/validate.sh"
source "${BASH_LIB}/log/utils.sh"


USAGE="tmux-shift-window -d l[eft]|r[ight] [-n num] {flags}"

usage() {
    echo "usage: ${USAGE}"
}

help() {
cat <<help
DESCRIPTION

    Shifts tmux windows -n windows in the direction provided by -d.

USAGE

    ${USAGE}

OPTIONS

    -d, --direction     l[eft] or r[ight]; the direction in which to shift the window
    -n, --num           optional, defaults to 1; integer; the number of places to shift the window

FLAGS

    -h, --help          display this message
help
}


DIRECTION=""
NUM="1"

LogFlags::process_log_flags "$@"

while [[ $# -gt 0 ]]; do
  case $1 in
    -d|--direction)
      [[ -n "${2:-}" ]] && DIRECTION="${2:-}" ; [[ -n "${2:-}" ]] && shift ; shift ;;
    -n|--num)
      [[ -n "${2:-}" ]] && NUM="${2:-}" ; [[ -n "${2:-}" ]] && shift ; shift ;;
    -v*|-q*)
      shift ;;
    -h|--help)
      help && exit 0 ;;
    *)
      ulogger error "$(usage)" && exit 1 ;;
  esac
done


validate_required "-d|--direction" "${DIRECTION}" || exit 1
validate_one_of "-d|--direction" "${DIRECTION}" "l" "left" "r" "right" || exit 1

SIGN="$([[ "${DIRECTION}" =~ l(eft)? ]] && echo "-" || echo "+")"
TO_SHIFT_IDX="$(tmux::window_idx)"
# shellcheck disable=SC1102
# shellcheck disable=SC2086
NEW_IDX=$(($TO_SHIFT_IDX "${SIGN}" $NUM))

SESSION_NAME="$(tmux::session_name)"
WINDOW_NAME="$(tmux::window_name)"
ulogger info "moving window=${WINDOW_NAME} in session=${SESSION_NAME} from position $TO_SHIFT_IDX to $NEW_IDX"

ERR="$(tmux swap-window -d -s "${SESSION_NAME}:${TO_SHIFT_IDX}" -t "${SESSION_NAME}:${NEW_IDX}" 2>&1)" || true
if [[ -n "${ERR}" ]]; then ulogger error "${ERR}" && exit 1 ; fi

