#!/usr/bin/env bash

set -Eeuo pipefail


mv /home/austin/Downloads/librewolf-stg-backups/* /home/austin/Backups/Browsers/librewolf/simple-tab-groups
rm -rf /home/austin/Downloads/librewolf-stg-backups

